// Auto-generated from https://pool.cpit.app/swagger/v1/swagger.json
// All enum values and schema structures for prefill validation

export const SparteTypeEnum = ["Rlv", "Bu", "Kfz", "Pr", "Br", "Kvv", "Kvz", "Hr", "Wg", "Gf", "Phv"] as const;

// ──── Shared Enums ────

export const enums: Record<string, readonly string[]> = {
  SparteTypeEnum,
  GeschlechtEnum: ["Maennlich", "Weiblich", "Divers"],
  FamilienstandEnum: ["Ledig", "Verheiratet", "Geschieden", "Verwitwet", "GetrenntLebend", "Eheaehnlich_eGemeinschaft", "Eingetragene_Lebenspartnerschaft", "Sonstiges"],
  AnredeEnum: ["Unbekannt", "Herr", "Frau", "Divers"],
  PersonenAnredeEnum: ["Herr", "Frau", "Unbekannt"],
  TitelEnum: ["Dr", "Prof"],
  PersonTypEnum: ["NATURAL_PERSON", "LEGAL_PERSON"],
  ZahlungsweiseEnum: ["Jaehrlich", "Halbjaehrlich", "Vierteljaehrlich", "Monatlich"],
  InflationsschutzEnum: ["Keine", "Percent1", "Percent2", "Percent3", "Percent4", "Percent5", "Percent6", "Percent7", "Percent8", "Percent9", "Percent10"],
  VorgabewunschEnum: ["GarantierteRente", "Beitrag"],
  KarenzzeitEnum: ["Keine", "Karenzzeit6Monate", "Karenzzeit12Monate", "Karenzzeit18Monate", "Karenzzeit24Monate"],
  GarantierteRentensteigerungEnum: ["Keine", "Percent1", "Percent2", "Percent3"],
  LaufzeitEnum: ["L1Jahr", "L3Jahre", "L5Jahre"],
  BeschaeftigungsartEnum: ["Privatwirtschaft", "OeffentlicherDienst"],

  // Beruf
  BerufsstatusEnum: ["Angestellter", "AngestellterImOeffentlichenDienst", "Auszubildender", "BeamterAufLebenszeit", "BeamterAufWiderruf", "BeamterAufProbe", "Freiberufler", "HausFrauMann", "Rentner", "Schueler", "Selbststaendiger", "Soldat", "Student", "UnbeschaeftigtNichtErwerbstaetig"],
  BildungsabschlussEnum: ["SchulischeAusbildung", "BeruflicheAusbildung", "Studium"],
  AbschlussEnum: ["Kein_Abschluss", "Hauptschulabschluss", "Qualifizierter_Hauptschulabschluss", "MittlereReife", "Fachabitur", "Abitur", "Bachelor_Fachhochschule", "Bachelor_Universitaet", "Master_Fachhochschule", "Master_Universitaet", "Diplom_Fachhochschule", "Diplom_Magister", "Staatsexamen_Universitaet", "Promotion", "Meister", "Techniker", "Fachschule", "Hochschulabschluss", "KaufmaennischeAusbildung", "HandwerklicheAusbildung", "SonstigeAusbildung", "WeiterbildungzumTechniker", "WeiterbildungzumFachBetriebswirt"],
  BerufTaetigkeitsumfangEnum: ["Vollzeit", "Teilzeit", "Geringfuegig_Beschaeftigt", "Saisonarbeiter"],
  TaetigkeitsstatusEnum: ["Unbefristet", "BefristetSechsMonate", "WiederholtBefristet", "Befristet"],
  BesoldungsgruppeEnum: ["A2", "A3", "A4", "A5", "A6", "A7", "A8", "A9", "A10", "A11", "A12", "A13", "A14", "A15", "A16", "B1", "B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9", "B10", "B11", "R1", "R2", "R3", "R4", "R5", "R6", "R7", "R8", "R9", "R10", "W1", "W2", "W3"],
  SchulformEnum: ["Ohne_Naehere_Bezeichnung", "Grundschule", "Hauptschule", "Mittelschule", "Realschule", "Stadtteilschule", "Werkrealschule", "Gesamtschule", "Oberschule", "Fachschule", "Gemeinschaftsschule", "Gymnasium_Bis_Klasse_10", "Gymnasium_Ab_Klasse_11", "Gymnasiale_Oberstufe", "Sonderschule", "Foerderschule", "Montessorischule", "Waldorfschule", "Privatschule"],
  VerhaeltnisZumVersicherungsnehmerEnum: ["Ehepartner", "LebenspartnerInHaeuslicherGemeinschaft", "Kind", "Elternteil", "BruderSchwester", "Großeltern", "Sonstige"],
  RauchverhaltenEnum: ["Raucher", "Mind1JahrNichtRaucher", "Mind10JahreNichtRaucher"],

  // KFZ
  FahrzeugtypEnum: ["PKW"],
  NeuOderWechselEnum: ["Neueanschaffung", "Versicherungswechsel"],
  ContractStartOptionEnum: ["Zum0101NaechstesJahr", "AndererVertragsbeginn"],
  ZulassungsartEnum: ["Ganzjährig", "Saison"],
  MonateEnum: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
  ZahlungsartKfzEnum: ["LASTSCHRIFT", "RECHNUNG"],
  FahrzeugfinanzierungEnum: ["EIGENTUM_VERSICHERUNGSNEHMER", "LEASING", "EIGENTUM_FINANZIERUNG"],
  GaragenartEnum: ["CARPORT", "ABSCHLIESSBARE_EINZEL_DOPPEL", "GESICHERTES_GRUNDSTUECK", "MEHRFACH_TIEFGARAGE_NICHT_ABSCHLIESSBAR", "NICHT_VORHANDEN"],
  NutzungsartKfzEnum: ["AUSSCHLIESSLICH_PRIVAT", "PRIVAT_UND_GESCHAEFTLICH", "AUSSCHLIESSLICH_GESCHAEFTLICH"],
  FahrtzweckEnum: ["DRUG_DELIVERY", "AUTOMATIC_LOADING", "AUTOMOBILE_TRADE", "MANAGEMENT_VEHICLE", "COMMERCIAL_TRAVEL", "TRADE_CRAFT_BUSINESS", "CUSTOMER_SERVICE", "COURIER_SERVICE", "DELIVERY_SERVICE", "PASSENGER_CAR", "NURSING_SERVICE", "PRIVATE_OR_MANAGEMENT", "SHOWMAN", "SELF_DRIVE_RENTAL", "SOCIAL_PURPOSES", "CARRIER", "TAXI", "DELIVERY_AGAINST_PAYMENT", "DELIVERY_NO_PAYMENT"],
  DeckungsumfangEnum: ["NUR_HAFTPFLICHT", "MIT_TEILKASKO", "MIT_VOLLKASKO"],
  SelbstbeteiligungEnum: ["OHNE", "SB_150EURO", "SB_300EURO", "SB_500EURO", "SB_1000EURO", "SB_2500EURO"],
  BeruflicheStellungEnum: ["ANGESTELLTE", "ANGESTELLTE_OEFFENTLICHE_DIENST", "ARBEITERIN", "ARBEITSLOS", "AZUBI", "BEAMTER", "FREIBERUFLER", "HAUSFRAU_HAUSMANN", "RENTNER", "SCHUELER_KIND", "SELBSTSTAENDIG", "STUDENTIN"],
  WohneigentumArtEnum: ["KEIN_WOHNEIGENTUM", "SELBSTGENUTZES_EIN_ZWEIFAMILIENHAUS", "EIGENTUMSWOHNUNG", "REIHENHAUS_DOPPELHAUSHAELFTE", "MEHRFAMILIENHAUS"],
  FahrzeugnutzerAuswahlNpEnum: ["AusschliesslichVersicherungsnehmer", "Jeder", "FestgelegterFahrerkreis", "FahrerkreisAltersangabe"],
  FahrzeugnutzerAuswahlLpEnum: ["Jeder", "FestgelegterFahrerkreis", "FahrerkreisAltersangabe"],
  FahrzeugnutzerAnzahlLpEnum: ["NurEinePerson", "MehrerePersonen"],
  VerhaeltnisZuVNEnum: ["SPOUSE", "PARTNER", "SOHN", "TOCHTER", "PARENT", "SIBLING", "GRANDPARENTS", "OTHER"],
  VerhaeltnisZuUnternehmenEnum: ["CEO", "COMPANY_OWNER", "EMPLOYEE", "SPECIFIED_USER", "SPOUSE_PARTNER_CEO_CO", "OTHER"],
  JaNeinWeissNichtEnum: ["Ja", "Nein", "IchWeissEsNicht"],
  SfKlassenOptionEnum: ["SF_KLASSEN_UEBERNEHMEN", "KEINE_SF_KLASSEN_VORHANDEN", "RABATT_VON_DRITTEN_UEBERNEHMEN"],
  RechtsformEnum: ["Einzelunternehmer", "Ag", "Gbr", "Gmbh", "GmbhCoKg", "Kg", "Ohg", "Sonstiges", "Ug", "UgCoKg", "Verein"],
  RechtsformKfzEnum: ["Einzelunternehmer", "Ag", "Gbr", "Gmbh", "GmbhCoKg", "Kg", "Ohg", "Sonstiges", "Ug", "UgCoKg", "Verein"],
  SchadenArtEnum: ["HAFTPFLICHT", "VOLLKASKO", "TEILKASKO"],
  KuendigungDurchEnum: ["VN_ZUM_ABLAUF", "VU_ZUM_ABLAUF", "UNGEKUENDIGT"],

  // BU
  BuTarifartEnum: ["Normal", "Starter"],
  BuUeberschussverwendungEnum: ["Beitragsverrechnung", "Bonusrente"],

  // RLV
  RlvArtEnum: ["Konstant", "Linear_Fallend", "Annuitaetisch_Fallend"],
  UeberschussverwendungRlvEnum: ["Beitragsverrechnung"],

  // BR (Basis-Rente)
  BrZahlungsweiseEnum: ["Jaehrlich", "Halbjaehrlich", "Vierteljaehrlich", "Monatlich", "Einmalzahlung"],
  BrTarifArtEnum: ["AufgeschobeneRente", "Sofortbeginnend"],
  BrVorgabewunschEnum: ["Beitrag", "MonatlicheGarantierente", "MonatlicheZielrente", "Einmalbeitrag"],
  BrGarantierteRentensteigerungEnum: ["Keine", "Percent1", "Percent2", "Percent3", "Percent4", "Percent5"],
  BrAbsicherungTodesfallEnum: ["KeineTodesfallleistung", "MindestensAuszahlungVertraguthabens", "MindestensRueckzahlungEingezahltenBeitraege", "MaximumEingezahltenBeitraegenVertragsguthaben"],
  BrTodesfallleistungEnum: ["Keine", "Rentengarantiezeit", "Kapitalrueckgewaehr"],
  BrRentengarantiezeitEnum: ["Value5", "Value10", "Value15", "Value20", "Value25", "Value30"],
  BrVergleichsberechnungEnum: ["Renditeorientiert", "Kostenguenstig", "Nachhaltig"],
  UeberschussverwendungNachRenteEnum: ["Investmentanlage", "DynamischeAnlage", "TeildynamischeRente", "FlexibleRente"],

  // PR (Privat-Rente)
  PrZahlungsweiseEnum: ["Jaehrlich", "Halbjaehrlich", "Vierteljaehrlich", "Monatlich", "Einmalzahlung"],
  PrTarifArtEnum: ["AufgeschobeneRente", "Sofortbeginnend", "Kindertarif"],
  PrVorgabewunschEnum: ["Beitrag", "MonatlicheGarantierente", "MonatlicheZielrente", "Einmalbeitrag"],
  PrGarantierteRentensteigerungEnum: ["Keine", "Percent1", "Percent2", "Percent3", "Percent4", "Percent5"],
  PrAbsicherungTodesfallEnum: ["KeineTodesfallleistung", "MindestensAuszahlungVertraguthabens", "MindestensRueckzahlungEingezahltenBeitraege", "MaximumEingezahltenBeitraegenVertragsguthaben"],
  PrTodesfallleistungEnum: ["Keine", "Rentengarantiezeit", "Kapitalrueckgewaehr"],
  PrRentengarantiezeitEnum: ["Value5", "Value10", "Value15", "Value20", "Value25", "Value30"],
  PrVergleichsberechnungEnum: ["Renditeorientiert", "Kostenguenstig", "Nachhaltig"],

  // GF (Grundfähigkeit)
  GfTarifartEnum: ["Normal", "Starter"],
  GfUeberschussverwendungEnum: ["Beitragsverrechnung", "Bonusrente"],

  // HR (Hausrat)
  GebaeudetypEnum: ["Einfamilienhaus", "Doppelhaushaelfte", "Zweifamilienhaus", "Reihenhaus", "Mehrfamilienhaus"],
  BauartklasseEnum: ["BAK1", "BAK2", "BAK3", "BAK4", "BAK5", "FHG1", "FHG2", "FHG3"],
  DacheindeckungEnum: ["HarteBedachung", "WeicheBedachung"],
  AussenwaendeBauweiseEnum: ["Massiv", "StahlHolzFachwerkFeuerhemmend", "StahlHolzFachwerkBeliebig", "Holz"],
  HrSelbstbeteiligungEnum: ["Null", "Hundertfuenfzig", "Dreihundert", "Fuenfhundert", "Tausend"],
  VersicherungssummeErmittlungsartEnum: ["AutomatischErmitteln", "EigeneVorgabe"],
  HrArtDesSchadensEnum: ["Feuer", "Einbruchdiebstahl", "Leitungswasser", "Sturm", "Elementar", "Starkregen", "Glas", "Fahrraddiebstahl"],

  // WG (Wohngebäude)
  NutzungsartEnum: ["Selbstbewohnt", "Vermietet", "Teilweisevermietet"],
  AnzahlVollgeschosseEnum: ["Vollgeschoss1", "Vollgeschoss2", "Vollgeschoss3", "Vollgeschoss4", "Vollgeschoss5", "Vollgeschoss6"],
  BrancheEnum: ["BueroKanzlei", "Apotheke", "BaeckereiBackwarenhandel", "BlumenPflanzenhandel", "FleischereiFleischwarenhandel", "Friseur", "GaststaetteRestaurant", "GeldKreditinstitute", "Getraenkehandel", "ArztpraxisHeilberufe", "ImbissKiosk", "KoerperpflegebetriebKosmetiksalon", "Lebensmittelhandel", "MedizinischesMassageinstitut", "ParfuemerieDrogerie", "SportstudioFitnesscenter", "ZahntechnischerBetriebDentallabor"],
  WertermittlungEnum: ["AutomatischErmitteln", "EigeneVorgabeWert1914", "BaugutachtenEur", "EigeneVorgabeEur"],
  BaustandardEnum: ["Gehoben", "Standard", "Einfach"],
  DachformEnum: ["GiebeldachAusgebaut", "GiebeldachNichtAusgebaut", "Flachdach"],
  WgFeuerrohbauEnum: ["Monate12", "Monate24", "Monate36"],
  WgSelbstbeteiligungEnum: ["Null", "Zweihundertfuenfzig", "Fuenfhundert", "Siebenhundertfuenfzig", "Tausend", "Eintausendfuenfhundert", "Zweitausend", "Zweitausendfuenfhundert"],
  WgArtDesSchadensEnum: ["Feuer", "Leitungswasser", "SturmHagel", "Elementar", "Starkregen", "Glas"],
  AnlagetypEnum: ["Photovoltaik", "Solarthermie", "Waermepumpe"],
  ModernisierungEnum: ["Rohre", "Elektrik", "Heizung", "Dach"],

  // KVV (Krankenversicherung Voll)
  PrimaerarztprinzipEnum: ["KeinPrimaerarztprinzip", "Primaerarztprinzip"],
  SehhilfenEnum: ["Mind300PA", "Egal", "Mind500PA", "Mind1000PA"],
  KvvGebuehrenordnungEnum: ["MindBisHoechstsatz", "OhneBegrenzung", "Egal"],
  NaturheilverfahrenEnum: ["Heilpraktiker", "Egal"],
  StationaerUnterkunftEnum: ["EinBettzimmer", "ZweiBettzimmer", "MehrBettzimmer"],
  StationaerWahlarztEnum: ["Ja", "Egal"],
  KvvDentaleLeistungenEnum: ["Prozent0", "Prozent50", "Prozent55", "Prozent60", "Prozent65", "Prozent70", "Prozent75", "Prozent80", "Prozent85", "Prozent90", "Prozent95", "Prozent100"],
  PflegepflichtEnum: ["Ja", "JaEhegattenkappung", "JaBeitragsfrei", "KeinePflegepflicht"],
  BeihilfeerganungEnum: ["Ja", "Nein"],
  BeihilfetraegerEnum: ["Bund", "BadenWuerttemberg", "Bayern", "Berlin", "Bradenburg", "Bremen", "Hamburg", "Hessen", "MecklenburgVorpommern", "Niedersachsen", "NordrheinWestfalen", "RheinlandPfalz", "Saarland", "Sachsen", "SachsenAnhalt", "SchleswigHolstein", "Thueringen"],
  AnzahlBeruecksichtigungsfaehigeKinderEnum: ["Null", "Eins", "Zwei", "Drei", "VierOderMehr"],
  KvvFamilienstandEnum: ["Verheiratet", "NichtVerheiratet"],
  BeihilfeProzentEnum: ["Prozent50", "Prozent55", "Prozent60", "Prozent65", "Prozent70", "Prozent75", "Prozent80", "Prozent85", "Prozent90"],
  KvvBeitragsentlastungArtEnum: ["MonatlicheEntlastungimAlter", "MonatlichenBeitrag", "MaxArbeitgeberzuschussAusschoepfen"],
  PflegetagegeldEnum: ["Pflegetagegeld", "Pflegekosten", "PflegeBahr"],
  KvKarenzzeitEnum: ["Ab4Tag", "Ab8Tag", "Ab15Tag", "Ab22Tag", "Ab29Tag", "Ab43Tag", "Ab64Tag", "Ab85Tag", "Ab92Tag", "Ab106Tag", "Ab127Tag", "Ab183Tag", "Ab274Tag", "Ab365Tag"],

  // KVZ (Krankenversicherung Zusatz)
  KvzStationaerUnterkunftEnum: ["EinBettzimmer", "ZweiBettzimmer", "Egal"],
  KvzStationaerWahlarztEnum: ["Ja", "Egal"],
  KvzGebuehrenordnungEnum: ["OhneBegrenzung", "Egal"],
  KvzDentaleLeistungenEnum: ["Prozent0", "Prozent5", "Prozent10", "Prozent15", "Prozent20", "Prozent25", "Prozent30", "Prozent35", "Prozent40", "Prozent45", "Prozent50", "Prozent55", "Prozent60", "Prozent65", "Prozent70", "Prozent75", "Prozent80", "Prozent85", "Prozent90", "Prozent95", "Prozent100"],
  SehhilfenPAEnum: ["Mind300PA", "Mind500PA", "Egal"],
  VorsorgeEnum: ["Mind150", "Mind300", "Egal"],
  PrivataerztlicheBehandlungEnum: ["Ja", "Nein"],
  ProfZahnreinigungPAEnum: ["Mind150", "Mind200", "Egal"],
  OptionAuchKvvEnum: ["Ja", "Nein"],
};

// ──── Field type definitions ────

export type FieldType = "string" | "integer" | "number" | "boolean" | "date-time" | "uuid" | "enum" | "object" | "array";

export interface FieldDef {
  type: FieldType;
  enumName?: string;
  nullable?: boolean;
  format?: string;
  objectSchema?: Record<string, FieldDef>;
  arrayItemSchema?: Record<string, FieldDef>;
  required?: string[];
}

// ──── Shared sub-schemas ────

const adresseFields: Record<string, FieldDef> = {
  plz: { type: "string", nullable: true },
  ort: { type: "string", nullable: true },
  strasse: { type: "string", nullable: true },
  hausnummer: { type: "string", nullable: true },
};

const grunddatenFields: Record<string, FieldDef> = {
  vertragsbeginn: { type: "string", format: "date-time", nullable: true },
};

const risikoDatenFields: Record<string, FieldDef> = {
  raucher: { type: "boolean", nullable: true },
  nichtRaucherSeitMind10Jahren: { type: "boolean", nullable: true },
  koerperLaenge: { type: "integer", nullable: true },
  koerperGewicht: { type: "integer", nullable: true },
  motorradfahrer: { type: "boolean", nullable: true },
  versichererHobbies: { type: "array", nullable: true, arrayItemSchema: {
    versichererId: { type: "string", format: "uuid", nullable: true },
    hobbyId: { type: "string", nullable: true },
    hobbyName: { type: "string", nullable: true },
  }},
};

const ausbildungUndBerufFields: Record<string, FieldDef> = {
  berufsbezeichnung: { type: "string", nullable: true },
  versichererBerufe: { type: "array", nullable: true, arrayItemSchema: {
    versichererId: { type: "string", format: "uuid", nullable: true },
    berufId: { type: "string", nullable: true },
    berufName: { type: "string", nullable: true },
    berufGruppe: { type: "string", nullable: true },
    trefferwahrscheinlichkeit: { type: "number", nullable: true },
    istArzt: { type: "boolean", nullable: true },
  }},
  berufsstatus: { type: "enum", enumName: "BerufsstatusEnum", nullable: true },
  aktuelleSchulform: { type: "enum", enumName: "SchulformEnum", nullable: true },
  studienrichtung: { type: "string", nullable: true },
  hoechsterBildungsabschluss: { type: "enum", enumName: "BildungsabschlussEnum", nullable: true },
  abschluss: { type: "enum", enumName: "AbschlussEnum", nullable: true },
  taetigkeitsumfag: { type: "enum", enumName: "BerufTaetigkeitsumfangEnum", nullable: true },
  mitarbeiteranzahl: { type: "integer", nullable: true },
  koerperlicheTaetigkeitInProzent: { type: "integer", nullable: true },
  buerotaetigkeitInProzent: { type: "integer", nullable: true },
  reisetaetigkeitInProzent: { type: "integer", nullable: true },
  chirurgischeTaeitgkeitInProzent: { type: "integer", nullable: true },
  selbsstaendigSeit: { type: "string", nullable: true },
  taetigkeitsstatus: { type: "enum", enumName: "TaetigkeitsstatusEnum", nullable: true },
  besoldungsgruppe: { type: "enum", enumName: "BesoldungsgruppeEnum", nullable: true },
};

const versichertePersonenItemFields: Record<string, FieldDef> = {
  geburtsdatum: { type: "string", format: "date-time", nullable: true },
  geschlecht: { type: "enum", enumName: "GeschlechtEnum", nullable: true },
  vorname: { type: "string", nullable: true },
  name: { type: "string", nullable: true },
  plz: { type: "string", nullable: true },
  ort: { type: "string", nullable: true },
  strasse: { type: "string", nullable: true },
  hausnummer: { type: "string", nullable: true },
  email: { type: "string", nullable: true },
  telefon: { type: "string", nullable: true },
  familienstand: { type: "enum", enumName: "FamilienstandEnum", nullable: true },
  verhaeltnisZumVersicherungsnehmer: { type: "enum", enumName: "VerhaeltnisZumVersicherungsnehmerEnum", nullable: true },
};

const versichertePersonenField: FieldDef = {
  type: "array",
  nullable: true,
  arrayItemSchema: versichertePersonenItemFields,
};

// ──── Sparte-specific prefill schemas ────

export const prefillSchemas: Record<string, { fields: Record<string, FieldDef> }> = {
  Kfz: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      einstieg: {
        type: "object",
        nullable: true,
        objectSchema: {
          fahrzeugtyp: { type: "enum", enumName: "FahrzeugtypEnum", nullable: true },
          neuOderWechsel: { type: "enum", enumName: "NeuOderWechselEnum", nullable: true },
          vertragsbeginnWechselOption: { type: "enum", enumName: "ContractStartOptionEnum", nullable: true },
          zulassungsart: { type: "enum", enumName: "ZulassungsartEnum", nullable: true },
          ichBinErstbesitzerDesFahrzeuges: { type: "boolean", nullable: true },
          erstzulassung: { type: "string", nullable: true },
          saisonAnfang: { type: "enum", enumName: "MonateEnum", nullable: true },
          insuranceBeginDate: { type: "string", nullable: true },
          saisonEnde: { type: "enum", enumName: "MonateEnum", nullable: true },
          zulassungAnDenHalter: { type: "string", nullable: true },
          unterjaehrigerAblauf: { type: "boolean", nullable: true },
          zahlungsweise: { type: "enum", enumName: "ZahlungsweiseEnum", nullable: true },
          zahlungsart: { type: "enum", enumName: "ZahlungsartKfzEnum", nullable: true },
        },
      },
      fahrzeug: {
        type: "object",
        nullable: true,
        objectSchema: {
          searchForHsn: { type: "string", nullable: true },
          searchForTsn: { type: "string", nullable: true },
          kennzeichenTeil1: { type: "string", nullable: true },
          kennzeichenTeil2: { type: "string", nullable: true },
          kennzeichenTeil3: { type: "string", nullable: true },
          kennzeichenTeil4: { type: "string", nullable: true },
          fahrzeugfinanzierung: { type: "enum", enumName: "FahrzeugfinanzierungEnum", nullable: true },
          neuwertDesFahrzeugsLiegtUeber80000: { type: "boolean", nullable: true },
          neuWert: { type: "number", nullable: true },
          garagenart: { type: "enum", enumName: "GaragenartEnum", nullable: true },
          fahrleistungProJahrKM: { type: "integer", nullable: true },
          nutzungsart: { type: "enum", enumName: "NutzungsartKfzEnum", nullable: true },
          fahrtzweck: { type: "enum", enumName: "FahrtzweckEnum", nullable: true },
          freeWorkshopSelection: { type: "boolean", nullable: true },
          schutzbrief: { type: "boolean", nullable: true },
          gapDeckung: { type: "boolean", nullable: true },
          fahrerschutz: { type: "boolean", nullable: true },
          rabattschutz: { type: "boolean", nullable: true },
          auslandsschutz: { type: "boolean", nullable: true },
        },
      },
      zurPerson: {
        type: "object",
        nullable: true,
        objectSchema: {
          personTyp: { type: "enum", enumName: "PersonTypEnum", nullable: true },
          vorname: { type: "string", nullable: true },
          nachname: { type: "string", nullable: true },
          geburtsdatum: { type: "string", nullable: true },
          fuehrerscheinerwerb: { type: "string", nullable: true },
          familienstand: { type: "enum", enumName: "FamilienstandEnum", nullable: true },
          beruflicheStellung: { type: "enum", enumName: "BeruflicheStellungEnum", nullable: true },
          wohneigentumArt: { type: "enum", enumName: "WohneigentumArtEnum", nullable: true },
          esGibtWeitereFahrer: { type: "boolean", nullable: true },
          branche: { type: "enum", enumName: "BrancheEnum", nullable: true },
          rechtsform: { type: "enum", enumName: "RechtsformEnum", nullable: true },
          unternehmenVorsteuerabzugsberechtigt: { type: "boolean", nullable: true },
          versicherungsnehmerPostleitzahl: { type: "string", nullable: true },
          npFahrzeugnutzerAuswahl: { type: "enum", enumName: "FahrzeugnutzerAuswahlNpEnum", nullable: true },
          lpFahrzeugnutzerAuswahl: { type: "enum", enumName: "FahrzeugnutzerAuswahlLpEnum", nullable: true },
          lpFahrzeugnutzerAnzahl: { type: "enum", enumName: "FahrzeugnutzerAnzahlLpEnum", nullable: true },
          npAlterJuengsterFahrer: { type: "string", nullable: true },
          npAlterAeltesterFahrer: { type: "string", nullable: true },
          lpAlterJuengsterFahrer: { type: "string", nullable: true },
          lpAlterAeltesterFahrer: { type: "string", nullable: true },
          npFahrkreis: { type: "array", nullable: true, arrayItemSchema: {
            verhaeltnis: { type: "enum", enumName: "VerhaeltnisZuVNEnum", nullable: true },
            geburtsdatum: { type: "string", nullable: true },
            begleitetesFahren: { type: "enum", enumName: "JaNeinWeissNichtEnum", nullable: true },
            vorname: { type: "string", nullable: true },
            nachname: { type: "string", nullable: true },
            licenseIssueDate: { type: "string", nullable: true },
          }},
          lpFahrkreis: { type: "array", nullable: true, arrayItemSchema: {
            verhaeltnis: { type: "enum", enumName: "VerhaeltnisZuUnternehmenEnum", nullable: true },
            geburtsdatum: { type: "string", nullable: true },
            begleitetesFahren: { type: "enum", enumName: "JaNeinWeissNichtEnum", nullable: true },
            vorname: { type: "string", nullable: true },
            nachname: { type: "string", nullable: true },
            licenseIssueDate: { type: "string", nullable: true },
          }},
          lpEinePersonGeburtsdatum: { type: "string", nullable: true },
          lpEinePersonVerhaeltnis: { type: "enum", enumName: "VerhaeltnisZuUnternehmenEnum", nullable: true },
          lpEinePersonFuehrerscheindatum: { type: "string", nullable: true },
          halterPostleitzahl: { type: "string", nullable: true },
          halter: { type: "string", nullable: true },
        },
      },
      sfKlassen: {
        type: "object",
        nullable: true,
        objectSchema: {
          lpSfKlassenQuelle: { type: "enum", enumName: "SfKlassenOptionEnum", nullable: true },
          npSfKlassenQuelle: { type: "enum", enumName: "SfKlassenOptionEnum", nullable: true },
          wUebernehmenSfkHaftpflicht: { type: "string", nullable: true },
          wUebernehmenSfkVollkasko: { type: "string", nullable: true },
          wUebernehmenKeineVollkasko: { type: "boolean", nullable: true },
          wUebernehmenVorversicherung: { type: "string", nullable: true },
          wUebernehmenHatSchaeden: { type: "boolean", nullable: true },
          wSchaeden: { type: "array", nullable: true, arrayItemSchema: {
            jahr: { type: "integer", nullable: true },
            art: { type: "enum", enumName: "SchadenArtEnum", nullable: true },
          }},
          npUebernehmenSfkHaftpflicht: { type: "string", nullable: true },
          npUebernehmenSfkVollkasko: { type: "string", nullable: true },
          npUebernehmenKeineVollkasko: { type: "boolean", nullable: true },
          npUebernehmenVorversicherung: { type: "string", nullable: true },
          npUebernehmenHatSchaeden: { type: "boolean", nullable: true },
          npSchaeden: { type: "array", nullable: true, arrayItemSchema: {
            jahr: { type: "integer", nullable: true },
            art: { type: "enum", enumName: "SchadenArtEnum", nullable: true },
          }},
          lpUebernehmenSfkHaftpflicht: { type: "string", nullable: true },
          lpUebernehmenSfkVollkasko: { type: "string", nullable: true },
          lpUebernehmenKeineVollkasko: { type: "boolean", nullable: true },
          lpUebernehmenVorversicherung: { type: "string", nullable: true },
          lpUebernehmenHatSchaeden: { type: "boolean", nullable: true },
          lpSchaeden: { type: "array", nullable: true, arrayItemSchema: {
            jahr: { type: "integer", nullable: true },
            art: { type: "enum", enumName: "SchadenArtEnum", nullable: true },
          }},
          drittenSfkHaftpflicht: { type: "string", nullable: true },
          drittenSfkVollkasko: { type: "string", nullable: true },
          drittenKeineVollkasko: { type: "boolean", nullable: true },
          lpWeiteresUnternehmenFahrzeugVersichert: { type: "boolean", nullable: true },
          lpFahrzeugsart: { type: "string", nullable: true },
          lpHalter: { type: "string", nullable: true },
          lpVersicherungsunternehmen: { type: "string", nullable: true },
          lpSfKlasse: { type: "string", nullable: true },
          lpNutzer: { type: "string", nullable: true },
          lpGeburtsdatumJuengsteNutzer: { type: "string", nullable: true },
          npWeiteresFamilienmitgliedVersichert: { type: "boolean", nullable: true },
          npFahrzeugsart: { type: "string", nullable: true },
          npVersicherungsnehmer: { type: "string", nullable: true },
          npHalter: { type: "string", nullable: true },
          npVersicherungsunternehmen: { type: "string", nullable: true },
          npSfKlasse: { type: "string", nullable: true },
          npNutzer: { type: "string", nullable: true },
          npGeburtsdatumJuengsteNutzer: { type: "string", nullable: true },
          eingeschraenkteBeratungsgrundlage: { type: "boolean", nullable: true },
          previousInsuranceDuration: { type: "string", nullable: true },
          deckungsumfang: { type: "enum", enumName: "DeckungsumfangEnum", nullable: true },
          uebernehmenSfkHaftpflicht: { type: "string", nullable: true },
          uebernehmenSfkVollkasko: { type: "string", nullable: true },
          selbstbeteiligungVollkasko: { type: "enum", enumName: "SelbstbeteiligungEnum", nullable: true },
          selbstbeteiligungTeilkasko: { type: "enum", enumName: "SelbstbeteiligungEnum", nullable: true },
          statutoryMinimumCoverageAmount: { type: "boolean", nullable: true },
        },
      },
      antrag: {
        type: "object",
        nullable: true,
        objectSchema: {
          email: { type: "string", nullable: true },
          mobilephoneNumber: { type: "string", nullable: true },
          vnNpAnrede: { type: "enum", enumName: "PersonenAnredeEnum", nullable: true },
          vnNpTitel: { type: "enum", enumName: "TitelEnum", nullable: true },
          vnNpVorname: { type: "string", nullable: true },
          vnNpNachname: { type: "string", nullable: true },
          vnNpStrasse: { type: "string", nullable: true },
          vnNpHausnummer: { type: "string", nullable: true },
          vnLpFirmenname: { type: "string", nullable: true },
          vnLpAnsprechpartner: { type: "string", nullable: true },
          vnLpStrasse: { type: "string", nullable: true },
          vnLpHausnummer: { type: "string", nullable: true },
          vnLpPlzStadt: { type: "string", nullable: true },
          hPersonTyp: { type: "enum", enumName: "PersonTypEnum", nullable: true },
          hNpAnrede: { type: "enum", enumName: "PersonenAnredeEnum", nullable: true },
          hNpTitel: { type: "enum", enumName: "TitelEnum", nullable: true },
          hNpVorname: { type: "string", nullable: true },
          hNpNachname: { type: "string", nullable: true },
          hNpStrasse: { type: "string", nullable: true },
          hNpHausnummer: { type: "string", nullable: true },
          hNpGeburtsdatum: { type: "string", nullable: true },
          hLpFirmenname: { type: "string", nullable: true },
          hLpRechtsform: { type: "enum", enumName: "RechtsformKfzEnum", nullable: true },
          hLpAnsprechpartner: { type: "string", nullable: true },
          hLpStrasse: { type: "string", nullable: true },
          hLpHausnummer: { type: "string", nullable: true },
          fahrzeugidentnummer: { type: "string", nullable: true },
          vvNpVersicherungscheinnummer: { type: "string", nullable: true },
          vvNpKennzeichenTeil1: { type: "string", nullable: true },
          vvNpKennzeichenTeil2: { type: "string", nullable: true },
          vvNpKennzeichenTeil3: { type: "string", nullable: true },
          vvNpKennzeichenTeil4: { type: "string", nullable: true },
          vvNpKuendigungDurch: { type: "enum", enumName: "KuendigungDurchEnum", nullable: true },
          nvNpVersicherungscheinnummer: { type: "string", nullable: true },
          nvNpKennzeichenTeil1: { type: "string", nullable: true },
          nvNpKennzeichenTeil2: { type: "string", nullable: true },
          nvNpKennzeichenTeil3: { type: "string", nullable: true },
          nvNpKennzeichenTeil4: { type: "string", nullable: true },
          vvLpVersicherungscheinnummer: { type: "string", nullable: true },
          vvLpKennzeichenTeil1: { type: "string", nullable: true },
          vvLpKennzeichenTeil2: { type: "string", nullable: true },
          vvLpKennzeichenTeil3: { type: "string", nullable: true },
          vvLpKennzeichenTeil4: { type: "string", nullable: true },
          vvLpKuendigungDurch: { type: "enum", enumName: "KuendigungDurchEnum", nullable: true },
          nvLpVersicherungscheinnummer: { type: "string", nullable: true },
          nvLpKennzeichenTeil1: { type: "string", nullable: true },
          nvLpKennzeichenTeil2: { type: "string", nullable: true },
          nvLpKennzeichenTeil3: { type: "string", nullable: true },
          nvLpKennzeichenTeil4: { type: "string", nullable: true },
          wvvVersicherungscheinnummer: { type: "string", nullable: true },
          wvvKennzeichenTeil1: { type: "string", nullable: true },
          wvvKennzeichenTeil2: { type: "string", nullable: true },
          wvvKennzeichenTeil3: { type: "string", nullable: true },
          wvvKennzeichenTeil4: { type: "string", nullable: true },
          wvvKuendigungDurch: { type: "enum", enumName: "KuendigungDurchEnum", nullable: true },
          versicherungsnehmerIstKontoinhaber: { type: "boolean", nullable: true },
          kiPersonTyp: { type: "enum", enumName: "PersonTypEnum", nullable: true },
          kiNpAnrede: { type: "enum", enumName: "PersonenAnredeEnum", nullable: true },
          kiNpTitel: { type: "enum", enumName: "TitelEnum", nullable: true },
          kiNpVorname: { type: "string", nullable: true },
          kiNpNachname: { type: "string", nullable: true },
          kiNpStrasse: { type: "string", nullable: true },
          kiNpHausnummer: { type: "string", nullable: true },
          kiNpPlzStadt: { type: "string", nullable: true },
          kiNpGeburtsdatum: { type: "string", nullable: true },
          kiLpFirmenname: { type: "string", nullable: true },
          kiLpRechtsform: { type: "enum", enumName: "RechtsformKfzEnum", nullable: true },
          kiLpAnsprechpartner: { type: "string", nullable: true },
          kiLpStrasse: { type: "string", nullable: true },
          kiLpHausnummer: { type: "string", nullable: true },
          kiLpPlzStadt: { type: "string", nullable: true },
          iban: { type: "string", nullable: true },
          bic: { type: "string", nullable: true },
          bankName: { type: "string", nullable: true },
          ichErmaechtigeZahlungeneinzuziehen: { type: "boolean", nullable: true },
          kmStand: { type: "integer", nullable: true },
        },
      },
    },
  },

  Bu: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          vertragsablaufAlter: { type: "integer", nullable: true },
          vertragsende: { type: "string", format: "date-time", nullable: true },
          monatsgenau: { type: "boolean", nullable: true },
          verlaengerteLeistungsdauer: { type: "boolean", nullable: true },
          ablaufLeistungzahlungAlter: { type: "integer", nullable: true },
          leistungssende: { type: "string", format: "date-time", nullable: true },
          normal: { type: "boolean", nullable: true },
          starter: { type: "boolean", nullable: true },
          tarifart: { type: "enum", enumName: "BuTarifartEnum", nullable: true },
          vorgabewunsch: { type: "enum", enumName: "VorgabewunschEnum", nullable: true },
          garantierteRente: { type: "number", nullable: true },
          beitragSumme: { type: "number", nullable: true },
          inflationsschutz: { type: "enum", enumName: "InflationsschutzEnum", nullable: true },
          ueberschussverwendung: { type: "enum", enumName: "BuUeberschussverwendungEnum", nullable: true },
          garantierteRentensteigerung: { type: "enum", enumName: "GarantierteRentensteigerungEnum", nullable: true },
          karenzzeit: { type: "enum", enumName: "KarenzzeitEnum", nullable: true },
          anzahlKinderImHaushalt: { type: "integer", nullable: true },
          familienstand: { type: "enum", enumName: "FamilienstandEnum", nullable: true },
          zahlungsweise: { type: "enum", enumName: "ZahlungsweiseEnum", nullable: true },
          selbstgenutztesWohneigentum: { type: "boolean", nullable: true },
        },
      },
      risikodaten: { type: "object", nullable: true, objectSchema: risikoDatenFields },
      beruf: { type: "object", nullable: true, objectSchema: ausbildungUndBerufFields },
      versichertePersonen: versichertePersonenField,
    },
  },

  Rlv: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          zahlungsweise: { type: "enum", enumName: "ZahlungsweiseEnum", nullable: true },
          verbundeneLeben: { type: "boolean", nullable: true },
          vertragsdauerInJahren: { type: "integer", nullable: true },
          versicherungssumme: { type: "integer", nullable: true },
          risikolebensversicherungArt: { type: "enum", enumName: "RlvArtEnum", nullable: true },
          zinssatzNominal: { type: "number", nullable: true },
          tilgungssatz: { type: "number", nullable: true },
          tilgungsfreieJahre: { type: "integer", nullable: true },
          ueberschussverwendung: { type: "enum", enumName: "UeberschussverwendungRlvEnum", nullable: true },
          beitragsbefreiungBeiBerufsunfaehigkeit: { type: "boolean", nullable: true },
          automatischeBeitragserhoehungDynamik: { type: "boolean", nullable: true },
          darlehnenabsicherung: { type: "boolean", nullable: true },
          darlehnshoehe: { type: "number", nullable: true },
          weiterereVersicherungenVorhanden: { type: "boolean", nullable: true },
          summeWeitererVersicherungen: { type: "number", nullable: true },
          anzahlKinderImHaushalt: { type: "integer", nullable: true },
          immobilienbesitz: { type: "boolean", nullable: true },
        },
      },
      risikodaten: { type: "object", nullable: true, objectSchema: risikoDatenFields },
      beruf: { type: "object", nullable: true, objectSchema: ausbildungUndBerufFields },
      versichertePersonen: versichertePersonenField,
    },
  },

  Br: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          zahlungsweise: { type: "enum", enumName: "BrZahlungsweiseEnum", nullable: true },
          vertragsablaufAlter: { type: "integer", nullable: true },
          rentenbeginnZumAlter: { type: "integer", nullable: true },
          rentenbeginn: { type: "string", format: "date-time", nullable: true },
          monatsgenau: { type: "boolean", nullable: true },
          familienstand: { type: "enum", enumName: "FamilienstandEnum", nullable: true },
          abgekuerzteBeitragszahlungsdauer: { type: "boolean", nullable: true },
          beitragszahlungBisAlter: { type: "integer", nullable: true },
          tarifArt: { type: "enum", enumName: "BrTarifArtEnum", nullable: true },
          vorgabewunsch: { type: "enum", enumName: "BrVorgabewunschEnum", nullable: true },
          vorgabewunschPrice: { type: "number", nullable: true },
          inflationsschutz: { type: "enum", enumName: "InflationsschutzEnum", nullable: true },
          garantierteRentensteigerung: { type: "enum", enumName: "BrGarantierteRentensteigerungEnum", nullable: true },
          zusaetzlicheEinmalzahlungBeginn: { type: "number", nullable: true },
          absicherungTodesfall: { type: "enum", enumName: "BrAbsicherungTodesfallEnum", nullable: true },
          todesfallleistung: { type: "enum", enumName: "BrTodesfallleistungEnum", nullable: true },
          rentengarantiezeit: { type: "enum", enumName: "BrRentengarantiezeitEnum", nullable: true },
          beitragsbefreiungBerufsunfaehigkeit: { type: "boolean", nullable: true },
          renteBerufsunfaehigkeit: { type: "boolean", nullable: true },
          garantierteBuRente: { type: "number", nullable: true },
          minimaleAltersrente: { type: "boolean", nullable: true },
          inflationsschutzBerufsunfaehigkeit: { type: "enum", enumName: "InflationsschutzEnum", nullable: true },
          garantierteRentensteigerungBerufsunfaehigkeit: { type: "enum", enumName: "BrGarantierteRentensteigerungEnum", nullable: true },
        },
      },
      risikodaten: { type: "object", nullable: true, objectSchema: risikoDatenFields },
      beruf: { type: "object", nullable: true, objectSchema: ausbildungUndBerufFields },
      garantienRendite: {
        type: "object",
        nullable: true,
        objectSchema: {
          iddBeratung: { type: "boolean", nullable: true },
          garantieniveauAnsparphaseVon: { type: "integer", nullable: true },
          garantieniveauAnsparphaseGewuenscht: { type: "integer", nullable: true },
          garantieniveauAnsparphaseBis: { type: "integer", nullable: true },
          vergleichsberechnung: { type: "enum", enumName: "BrVergleichsberechnungEnum", nullable: true },
          wertentwicklungNiedrig: { type: "number", nullable: true },
          wertentwicklungMittel: { type: "number", nullable: true },
          wertentwicklungHoch: { type: "number", nullable: true },
          ueberschussverwendungNachRente: { type: "enum", enumName: "UeberschussverwendungNachRenteEnum", nullable: true },
          investmentanlage: { type: "boolean", nullable: true },
          klassisch: { type: "boolean", nullable: true },
          indexpartizipation: { type: "boolean", nullable: true },
        },
      },
      versichertePersonen: versichertePersonenField,
    },
  },

  Pr: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          zahlungsweise: { type: "enum", enumName: "PrZahlungsweiseEnum", nullable: true },
          vertragsablaufAlter: { type: "integer", nullable: true },
          rentenbeginnZumAlter: { type: "integer", nullable: true },
          rentenbeginn: { type: "string", format: "date-time", nullable: true },
          monatsgenau: { type: "boolean", nullable: true },
          abgekuerzteBeitragszahlungsdauer: { type: "boolean", nullable: true },
          beitragszahlungBisAlter: { type: "integer", nullable: true },
          tarifArt: { type: "enum", enumName: "PrTarifArtEnum", nullable: true },
          vorgabewunsch: { type: "enum", enumName: "PrVorgabewunschEnum", nullable: true },
          vorgabewunschPrice: { type: "number", nullable: true },
          inflationsschutz: { type: "enum", enumName: "InflationsschutzEnum", nullable: true },
          garantierteRentensteigerung: { type: "enum", enumName: "PrGarantierteRentensteigerungEnum", nullable: true },
          zusaetzlicheEinmalzahlungBeginn: { type: "number", nullable: true },
          absicherungTodesfall: { type: "enum", enumName: "PrAbsicherungTodesfallEnum", nullable: true },
          todesfallleistung: { type: "enum", enumName: "PrTodesfallleistungEnum", nullable: true },
          rentengarantiezeit: { type: "enum", enumName: "PrRentengarantiezeitEnum", nullable: true },
          beitragsbefreiungBerufsunfaehigkeit: { type: "boolean", nullable: true },
        },
      },
      risikodaten: { type: "object", nullable: true, objectSchema: risikoDatenFields },
      beruf: { type: "object", nullable: true, objectSchema: ausbildungUndBerufFields },
      garantienRendite: {
        type: "object",
        nullable: true,
        objectSchema: {
          iddBeratung: { type: "boolean", nullable: true },
          garantieniveauAnsparphaseVon: { type: "integer", nullable: true },
          garantieniveauAnsparphaseGewuenscht: { type: "integer", nullable: true },
          garantieniveauAnsparphaseBis: { type: "integer", nullable: true },
          investmentanlage: { type: "boolean", nullable: true },
          klassisch: { type: "boolean", nullable: true },
          indexpartizipation: { type: "boolean", nullable: true },
          vergleichsberechnung: { type: "enum", enumName: "PrVergleichsberechnungEnum", nullable: true },
          wertentwicklungNiedrig: { type: "number", nullable: true },
          wertentwicklungMittel: { type: "number", nullable: true },
          wertentwicklungHoch: { type: "number", nullable: true },
          ueberschussverwendungNachRente: { type: "enum", enumName: "UeberschussverwendungNachRenteEnum", nullable: true },
        },
      },
      versichertePersonen: versichertePersonenField,
    },
  },

  Gf: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          vertragsablaufAlter: { type: "integer", nullable: true },
          vertragsende: { type: "string", format: "date-time", nullable: true },
          monatsgenau: { type: "boolean", nullable: true },
          verlaengerteLeistungsdauer: { type: "boolean", nullable: true },
          ablaufLeistungzahlungAlter: { type: "integer", nullable: true },
          leistungssende: { type: "string", format: "date-time", nullable: true },
          normal: { type: "boolean", nullable: true },
          starter: { type: "boolean", nullable: true },
          tarifart: { type: "enum", enumName: "GfTarifartEnum", nullable: true },
          vorgabewunsch: { type: "enum", enumName: "VorgabewunschEnum", nullable: true },
          garantierteRente: { type: "number", nullable: true },
          beitragSumme: { type: "number", nullable: true },
          inflationsschutz: { type: "enum", enumName: "InflationsschutzEnum", nullable: true },
          ueberschussverwendung: { type: "enum", enumName: "GfUeberschussverwendungEnum", nullable: true },
          garantierteRentensteigerung: { type: "enum", enumName: "GarantierteRentensteigerungEnum", nullable: true },
          karenzzeit: { type: "enum", enumName: "KarenzzeitEnum", nullable: true },
          anzahlKinderImHaushalt: { type: "integer", nullable: true },
          familienstand: { type: "enum", enumName: "FamilienstandEnum", nullable: true },
          zahlungsweise: { type: "enum", enumName: "ZahlungsweiseEnum", nullable: true },
          selbstgenutztesWohneigentum: { type: "boolean", nullable: true },
        },
      },
      risikodaten: { type: "object", nullable: true, objectSchema: risikoDatenFields },
      beruf: { type: "object", nullable: true, objectSchema: ausbildungUndBerufFields },
      versichertePersonen: versichertePersonenField,
    },
  },

  Hr: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          beschaeftigungsart: { type: "enum", enumName: "BeschaeftigungsartEnum", nullable: true },
          laufzeitJahre: { type: "enum", enumName: "LaufzeitEnum", nullable: true },
          zahlungsweise: { type: "enum", enumName: "ZahlungsweiseEnum", nullable: true },
          bauartklassenErmittlung: {
            type: "object", nullable: true, objectSchema: {
              dacheindeckung: { type: "enum", enumName: "DacheindeckungEnum", nullable: true },
              aussenwaendeBauweise: { type: "enum", enumName: "AussenwaendeBauweiseEnum", nullable: true },
              fertighaus: { type: "boolean", nullable: true },
            },
          },
          bauartklasse: { type: "enum", enumName: "BauartklasseEnum", nullable: true },
          gebaeudetyp: { type: "enum", enumName: "GebaeudetypEnum", nullable: true },
          anschriftVersicherungsnehmerUebernehmen: { type: "boolean", nullable: true },
          adresseDerWohnung: { type: "object", nullable: true, objectSchema: adresseFields },
          nutzungUndFlaeche: {
            type: "object", nullable: true, objectSchema: {
              wohnflaecheOhneKellerQm: { type: "number", nullable: true },
              staendigBewohnt: { type: "boolean", nullable: true },
              kellerVorhanden: { type: "boolean", nullable: true },
              gesamtflaecheKellerQm: { type: "number", nullable: true },
              wohnflaecheKellerQm: { type: "number", nullable: true },
            },
          },
        },
      },
      deckungsumfang: {
        type: "object",
        nullable: true,
        objectSchema: {
          zusatzschutz: {
            type: "object", nullable: true, objectSchema: {
              fahrraddiebstahl: { type: "boolean", nullable: true },
              glasbruch: { type: "boolean", nullable: true },
              elementar: { type: "boolean", nullable: true },
              ueberspannung: { type: "boolean", nullable: true },
            },
          },
          fahrradGesamtwertEur: { type: "integer", nullable: true },
          versicherungssummeErmittlungsart: { type: "enum", enumName: "VersicherungssummeErmittlungsartEnum", nullable: true },
          versicherungssummeEur: { type: "integer", nullable: true },
          selbstbehaltHausratBis: { type: "enum", enumName: "HrSelbstbeteiligungEnum", nullable: true },
          mindestsicherung: { type: "boolean", nullable: true },
          ueberwachungsanlage: { type: "boolean", nullable: true },
          vorversicherungVorhanden: { type: "boolean", nullable: true },
          schaedenInDenLetztenJahren: { type: "boolean", nullable: true },
          vorschaeden: { type: "array", nullable: true, arrayItemSchema: {
            artDesSchadens: { type: "enum", enumName: "HrArtDesSchadensEnum", nullable: true },
            jahrDesSchadens: { type: "integer", nullable: true },
            hoeheDesSchadens: { type: "integer", nullable: true },
          }},
        },
      },
    },
  },

  Wg: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          beschaeftigungsart: { type: "enum", enumName: "BeschaeftigungsartEnum", nullable: true },
          laufzeitJahre: { type: "enum", enumName: "LaufzeitEnum", nullable: true },
          zahlungsweise: { type: "enum", enumName: "ZahlungsweiseEnum", nullable: true },
          gebaeudetyp: { type: "enum", enumName: "GebaeudetypEnum", nullable: true },
          anzahlWohneinheiten: { type: "integer", nullable: true },
          anschriftVersicherungsnehmerUebernehmen: { type: "boolean", nullable: true },
          adresseDesGebaeudes: { type: "object", nullable: true, objectSchema: adresseFields },
          gebaeudeEigenschaften: {
            type: "object", nullable: true, objectSchema: {
              bauartklassenErmittlung: {
                type: "object", nullable: true, objectSchema: {
                  dacheindeckung: { type: "enum", enumName: "DacheindeckungEnum", nullable: true },
                  aussenwaendeBauweise: { type: "enum", enumName: "AussenwaendeBauweiseEnum", nullable: true },
                  fertighaus: { type: "boolean", nullable: true },
                },
              },
              bauartklasse: { type: "enum", enumName: "BauartklasseEnum", nullable: true },
              baujahr: { type: "integer", nullable: true },
              dachform: { type: "enum", enumName: "DachformEnum", nullable: true },
              denkmalschutz: { type: "boolean", nullable: true },
              feuerrohbau: { type: "boolean", nullable: true },
              feuerrohbauEnum: { type: "enum", enumName: "WgFeuerrohbauEnum", nullable: true },
            },
          },
          wgNutzungFlaeche: {
            type: "object", nullable: true, objectSchema: {
              nutzungsart: { type: "enum", enumName: "NutzungsartEnum", nullable: true },
              staendigBewohnt: { type: "boolean", nullable: true },
              wohnflaecheOhneKellerQm: { type: "integer", nullable: true },
              anzahlVollgeschosse: { type: "enum", enumName: "AnzahlVollgeschosseEnum", nullable: true },
              kellerVorhanden: { type: "boolean", nullable: true },
              gesamtflaecheImKellerQm: { type: "integer", nullable: true },
              wohnflaecheImKellerQm: { type: "integer", nullable: true },
              gewerblicheNutzungImGebaeude: { type: "boolean", nullable: true },
              anzahlGewerbeeinheiten: { type: "integer", nullable: true },
              gewerbeflaecheQm: { type: "integer", nullable: true },
              branche: { type: "enum", enumName: "BrancheEnum", nullable: true },
            },
          },
          garageCarport: {
            type: "object", nullable: true, objectSchema: {
              anzahlGaragenOderStellplaetze: { type: "integer", nullable: true },
              anzahlCarports: { type: "integer", nullable: true },
            },
          },
          nebengebaeudeVorhanden: { type: "boolean", nullable: true },
          nebengebaeudeList: { type: "array", nullable: true, arrayItemSchema: {
            bezeichnung: { type: "string", nullable: true },
            nutzflaeche: { type: "integer", nullable: true },
          }},
        },
      },
      ausfuehrung: {
        type: "object",
        nullable: true,
        objectSchema: {
          tarifart: {
            type: "object", nullable: true, objectSchema: {
              wohnflaechentarif: { type: "boolean", nullable: true },
              summentarif: { type: "boolean", nullable: true },
            },
          },
          wertermittlung: { type: "enum", enumName: "WertermittlungEnum", nullable: true },
          wertermittlungEigeneVorgabe: { type: "integer", nullable: true },
          baustandard: { type: "enum", enumName: "BaustandardEnum", nullable: true },
          baustandardDetails: {
            type: "object", nullable: true, objectSchema: {
              dachNaturschieferOderKupfer: { type: "boolean", nullable: true },
              aussenwaendeNaturKeramikKunststeinKlinker: { type: "boolean", nullable: true },
              innenausbauStuckOderEdelholz: { type: "boolean", nullable: true },
              fussboedenNatursteinOderParkett: { type: "boolean", nullable: true },
              fussboedenPvcAufEstrich: { type: "boolean", nullable: true },
              fensterLeichtmetallUndHolzsprossen: { type: "boolean", nullable: true },
              fensterEinfachverglasung: { type: "boolean", nullable: true },
              tuerenEdelholz: { type: "boolean", nullable: true },
              sanitaerHochwertig: { type: "boolean", nullable: true },
              sanitaerOhneBadOderDusche: { type: "boolean", nullable: true },
              heizungFussbodenOderDecke: { type: "boolean", nullable: true },
              heizungOfenOderNachtspeicher: { type: "boolean", nullable: true },
              kuecheHochwertigeEinbaukueche: { type: "boolean", nullable: true },
            },
          },
          photovoltaikVorhanden: { type: "boolean", nullable: true },
          photovoltaikDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "AnlagetypEnum", nullable: true },
              anschaffungswert: { type: "integer", nullable: true },
              maximaleLeistung: { type: "integer", nullable: true },
              anschaffungsjahr: { type: "integer", nullable: true },
            },
          },
          solarthermieVorhanden: { type: "boolean", nullable: true },
          solarthermieDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "AnlagetypEnum", nullable: true },
              anschaffungswert: { type: "integer", nullable: true },
              maximaleLeistung: { type: "integer", nullable: true },
              anschaffungsjahr: { type: "integer", nullable: true },
            },
          },
          waermepumpeVorhanden: { type: "boolean", nullable: true },
          waermepumpeDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "AnlagetypEnum", nullable: true },
              anschaffungswert: { type: "integer", nullable: true },
              maximaleLeistung: { type: "integer", nullable: true },
              anschaffungsjahr: { type: "integer", nullable: true },
            },
          },
          gebaeudeWurdeKernsaniert: { type: "boolean", nullable: true },
          jahrDerLetztenKernsanierung: { type: "integer", nullable: true },
          einzelneBereicheWurdenSaniert: { type: "boolean", nullable: true },
          teilsanierungRohre: { type: "boolean", nullable: true },
          teilsanierungRohreDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "ModernisierungEnum", nullable: true },
              jahr: { type: "integer", nullable: true },
            },
          },
          teilsanierungElektrik: { type: "boolean", nullable: true },
          teilsanierungElektrikDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "ModernisierungEnum", nullable: true },
              jahr: { type: "integer", nullable: true },
            },
          },
          teilsanierungHeizung: { type: "boolean", nullable: true },
          teilsanierungHeizungDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "ModernisierungEnum", nullable: true },
              jahr: { type: "integer", nullable: true },
            },
          },
          teilsanierungDach: { type: "boolean", nullable: true },
          teilsanierungDachDetails: {
            type: "object", nullable: true, objectSchema: {
              typ: { type: "enum", enumName: "ModernisierungEnum", nullable: true },
              jahr: { type: "integer", nullable: true },
            },
          },
        },
      },
      deckungsumfang: {
        type: "object",
        nullable: true,
        objectSchema: {
          grundElementarschutz: {
            type: "object", nullable: true, objectSchema: {
              feuer: { type: "boolean", nullable: true },
              leitungswasser: { type: "boolean", nullable: true },
              sturmHagel: { type: "boolean", nullable: true },
              elementar: { type: "boolean", nullable: true },
              glas: { type: "boolean", nullable: true },
            },
          },
          photovoltaik: { type: "boolean", nullable: true },
          solarthermie: { type: "boolean", nullable: true },
          waermepumpe: { type: "boolean", nullable: true },
          selbstbeteiligung: { type: "enum", enumName: "WgSelbstbeteiligungEnum", nullable: true },
          vorversicherungIstVorhanden: { type: "boolean", nullable: true },
          schaedenInDenLetztenJahren: { type: "boolean", nullable: true },
          vorschaeden: { type: "array", nullable: true, arrayItemSchema: {
            artDesSchadens: { type: "enum", enumName: "WgArtDesSchadensEnum", nullable: true },
            jahrDesSchadens: { type: "integer", nullable: true },
            hoeheDesSchadens: { type: "integer", nullable: true },
          }},
          feuerrohbauDeckung: { type: "boolean", nullable: true },
        },
      },
    },
  },

  Kvv: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
          arzttarife: {
            type: "object", nullable: true, objectSchema: {
              normalTarife: { type: "boolean", nullable: true },
              arztTarife: { type: "boolean", nullable: true },
              zahnArztTarife: { type: "boolean", nullable: true },
            },
          },
          beihilfeAngaben: {
            type: "object", nullable: true, objectSchema: {
              beihilfetraeger: { type: "enum", enumName: "BeihilfetraegerEnum", nullable: true },
              anzahlBeruecksichtigungsfaehigeKinder: { type: "enum", enumName: "AnzahlBeruecksichtigungsfaehigeKinderEnum", nullable: true },
              familienstand: { type: "enum", enumName: "KvvFamilienstandEnum", nullable: true },
              ehepartnerBeruecksichtigungsfaehig: { type: "boolean", nullable: true },
              beihilfesatzAngabenAutomatischErmitteln: { type: "boolean", nullable: true },
              beihilfesatzAmbulant: { type: "enum", enumName: "BeihilfeProzentEnum", nullable: true },
              esBestehtBeihilfeanspruchStationaer: { type: "boolean", nullable: true },
            },
          },
        },
      },
      leistungsumfang: {
        type: "object",
        nullable: true,
        objectSchema: {
          selbstbehalt: {
            type: "object", nullable: true, objectSchema: {
              selbstbehaltMin: { type: "number", nullable: true },
              selbstbehaltMax: { type: "number", nullable: true },
            },
          },
          ambulanteLeistungen: {
            type: "object", nullable: true, objectSchema: {
              primaerarztprinzip: { type: "enum", enumName: "PrimaerarztprinzipEnum", nullable: true },
              sehhilfen: { type: "enum", enumName: "SehhilfenEnum", nullable: true },
              gebuehrenordnungAmbulant: { type: "enum", enumName: "KvvGebuehrenordnungEnum", nullable: true },
              naturheilverfahren: { type: "enum", enumName: "NaturheilverfahrenEnum", nullable: true },
            },
          },
          stationaerLeistungen: {
            type: "object", nullable: true, objectSchema: {
              stationaerUnterkunft: { type: "enum", enumName: "StationaerUnterkunftEnum", nullable: true },
              stationaerWahlarzt: { type: "enum", enumName: "StationaerWahlarztEnum", nullable: true },
              gebuehrenordnungStationaer: { type: "enum", enumName: "KvvGebuehrenordnungEnum", nullable: true },
            },
          },
          dentaleLeistungen: {
            type: "object", nullable: true, objectSchema: {
              zahnbehandlung: { type: "enum", enumName: "KvvDentaleLeistungenEnum", nullable: true },
              zahnersatz: { type: "enum", enumName: "KvvDentaleLeistungenEnum", nullable: true },
              kieferorthopaedie: { type: "enum", enumName: "KvvDentaleLeistungenEnum", nullable: true },
              gebuehrenordnungDental: { type: "enum", enumName: "KvvGebuehrenordnungEnum", nullable: true },
            },
          },
          pflegepflicht: { type: "enum", enumName: "PflegepflichtEnum", nullable: true },
          beihilfeergaenzung: { type: "enum", enumName: "BeihilfeerganungEnum", nullable: true },
        },
      },
      ergaenzungen: {
        type: "object",
        nullable: true,
        objectSchema: {
          krankenhaustagegeldBoolean: { type: "boolean", nullable: true },
          krankenhaustagegeld: { type: "object", nullable: true, objectSchema: { tagessatz: { type: "number", nullable: true } } },
          kurtagegeldBoolean: { type: "boolean", nullable: true },
          kurtagegeld: { type: "object", nullable: true, objectSchema: { tagessatz: { type: "number", nullable: true } } },
          pflegezusatzBoolean: { type: "boolean", nullable: true },
          pflegezusatz: {
            type: "object", nullable: true, objectSchema: {
              pflegetagegeld: { type: "enum", enumName: "PflegetagegeldEnum", nullable: true },
              pflegegradEinAmbulant: { type: "number", nullable: true },
              pflegegradZweiAmbulant: { type: "number", nullable: true },
              pflegegradDreiAmbulant: { type: "number", nullable: true },
              pflegegradVierAmbulant: { type: "number", nullable: true },
              pflegegradFunfAmbulant: { type: "number", nullable: true },
              pflegegradEinStationar: { type: "number", nullable: true },
              pflegegradZweiStationar: { type: "number", nullable: true },
              pflegegradDreiStationar: { type: "number", nullable: true },
              pflegegradVierStationar: { type: "number", nullable: true },
              pflegegradFunfStationar: { type: "number", nullable: true },
            },
          },
          krankentagegeldBoolean: { type: "boolean", nullable: true },
          krankentagegeld: { type: "array", nullable: true, arrayItemSchema: {
            tagessatz: { type: "number", nullable: true },
            karenzzeit: { type: "enum", enumName: "KvKarenzzeitEnum", nullable: true },
          }},
          beitragsentlastungBoolean: { type: "boolean", nullable: true },
          beitragsentlastung: {
            type: "object", nullable: true, objectSchema: {
              beitragsentlastungArt: { type: "enum", enumName: "KvvBeitragsentlastungArtEnum", nullable: true },
              entlastungKVBeitrag: { type: "number", nullable: true },
              beitrag: { type: "number", nullable: true },
              beitagsentlastungAbAlter: { type: "number", nullable: true },
              eigenanteil: { type: "number", nullable: true },
            },
          },
          alternativKurleistung: { type: "boolean", nullable: true },
        },
      },
      versichertePersonen: versichertePersonenField,
    },
  },

  Kvz: {
    fields: {
      sparte: { type: "enum", enumName: "SparteTypeEnum" },
      grunddaten: {
        type: "object",
        nullable: true,
        objectSchema: {
          ...grunddatenFields,
        },
      },
      leistungsumfang: {
        type: "object",
        nullable: true,
        objectSchema: {
          ambulanteLeistungenBoolean: { type: "boolean", nullable: true },
          ambulanteLeistungen: {
            type: "object", nullable: true, objectSchema: {
              sehhilfen: { type: "enum", enumName: "SehhilfenPAEnum", nullable: true },
              naturheilverfahren: { type: "number", nullable: true },
              vorsorge: { type: "enum", enumName: "VorsorgeEnum", nullable: true },
              privataerztlicheBehandlung: { type: "enum", enumName: "PrivataerztlicheBehandlungEnum", nullable: true },
            },
          },
          stationaerLeistungenBoolean: { type: "boolean", nullable: true },
          stationaerLeistungen: {
            type: "object", nullable: true, objectSchema: {
              stationaerUnterkunft: { type: "enum", enumName: "KvzStationaerUnterkunftEnum", nullable: true },
              stationaerWahlarzt: { type: "enum", enumName: "KvzStationaerWahlarztEnum", nullable: true },
              gebuehrenordnungStationaer: { type: "enum", enumName: "KvzGebuehrenordnungEnum", nullable: true },
            },
          },
          dentaleLeistungenBoolean: { type: "boolean", nullable: true },
          dentaleLeistungen: {
            type: "object", nullable: true, objectSchema: {
              zahnersatz: { type: "enum", enumName: "KvzDentaleLeistungenEnum", nullable: true },
              zahnbehandlung: { type: "enum", enumName: "KvzDentaleLeistungenEnum", nullable: true },
              kieferorthopaedie: { type: "enum", enumName: "KvzDentaleLeistungenEnum", nullable: true },
              profZahnreinigungPA: { type: "enum", enumName: "ProfZahnreinigungPAEnum", nullable: true },
            },
          },
          optionstarifeBoolean: { type: "boolean", nullable: true },
          optionstarife: {
            type: "object", nullable: true, objectSchema: {
              optionAuchKvv: { type: "enum", enumName: "OptionAuchKvvEnum", nullable: true },
            },
          },
          krankenhaustagegeldBoolean: { type: "boolean", nullable: true },
          krankenhaustagegeld: { type: "object", nullable: true, objectSchema: { tagessatz: { type: "number", nullable: true } } },
          kurtagegeldBoolean: { type: "boolean", nullable: true },
          kurtagegeld: { type: "object", nullable: true, objectSchema: { tagessatz: { type: "number", nullable: true } } },
          pflegezusatzBoolean: { type: "boolean", nullable: true },
          pflegezusatz: {
            type: "object", nullable: true, objectSchema: {
              pflegetagegeld: { type: "enum", enumName: "PflegetagegeldEnum", nullable: true },
              pflegegradEinAmbulant: { type: "number", nullable: true },
              pflegegradZweiAmbulant: { type: "number", nullable: true },
              pflegegradDreiAmbulant: { type: "number", nullable: true },
              pflegegradVierAmbulant: { type: "number", nullable: true },
              pflegegradFunfAmbulant: { type: "number", nullable: true },
              pflegegradEinStationar: { type: "number", nullable: true },
              pflegegradZweiStationar: { type: "number", nullable: true },
              pflegegradDreiStationar: { type: "number", nullable: true },
              pflegegradVierStationar: { type: "number", nullable: true },
              pflegegradFunfStationar: { type: "number", nullable: true },
            },
          },
          krankentagegeldBoolean: { type: "boolean", nullable: true },
          krankentagegeld: { type: "array", nullable: true, arrayItemSchema: {
            tagessatz: { type: "number", nullable: true },
            karenzzeit: { type: "enum", enumName: "KvKarenzzeitEnum", nullable: true },
          }},
        },
      },
      versichertePersonen: versichertePersonenField,
    },
  },
};
